type : FCOSMono3D
backbone :
    type : ResNet
    depth : 101
    num_stages : 4
    out_indices : [0, 1, 2, 3]
    frozen_stages : 1
    norm_cfg :
        type : BN
        requires_grad : false
    norm_eval : true
    style : 'caffe'
    init_cfg :
        type : Pretrained
        checkpoint : 'open-mmlab://detectron2/resnet101_caffe'


neck :
    type : FPN
    in_channels : [256, 512, 1024, 2048]
    out_channels : 256
    start_level : 1
    add_extra_convs : on_output
    num_outs : 5
    relu_before_extra_convs : true

bbox_head :
    type : FCOSMono3DHead
    num_classes : 1
    in_channels : 256
    stacked_convs : 2
    feat_channels : 256
    center_sample_radius : 1.5
    centerness_alpha : 2.5
    use_direction_classifier : false
    diff_rad_by_sin : true
    pred_attrs : false
    pred_velo : true
    dir_offset : 0.7854
    dir_limit_offset : 0
    strides : [8, 16, 32, 64, 128]
    group_reg_dims : [2, 1, 3, 1, 2]
    cls_branch : [256]
    reg_branch : [[256], [256], [256], [256], []]
    dir_branch : [256]
    attr_branch : [256]
    loss_cls : 
        type : 'FocalLoss'
        use_sigmoid : True
        gamma : 2.0
        alpha : 0.25
        loss_weight : 1.0
    loss_bbox :
        type : SmoothL1Loss
        beta : 0.1111111111111111
        loss_weight : 1.0
    loss_dir :
        type : CrossEntropyLoss
        use_sigmoid : false
        loss_weight : 1.0
    loss_attr :
        type : 'CrossEntropyLoss'
        use_sigmoid : False
        loss_weight : 0
    loss_centerness :
        type : CrossEntropyLoss
        use_sigmoid : true
        loss_weight : 1.0
    bbox_coder :
        type : FCOS3DBBoxCoder
        code_size : 9
    norm_on_bbox : true
    centerness_on_reg : true
    center_sampling : true
    conv_bias : true
    dcn_on_last_conv : true

train_cfg :
    allowed_border : 0
    code_weight : [1.0, 1.0, 0.2, 1.0, 1.0, 1.0, 1.0, 0.05, 0.05]
    pos_weight : -1
    debug: False

test_cfg :
    use_rotate_nms : True
    nms_across_levels : False
    nms_pre : 1000
    nms_thr : 0.2
    score_thr : 0.1
    min_bbox_size : 0
    max_per_img : 200