type : 'MultiViewDfMFisheye'
vehicle : 'Hycan'
num_views : 4
num_ref_frames : 0
backbone : 
    type : 'ResNet'
    depth : 50
    num_stages : 4
    out_indices : [0, 1, 2, 3]
    frozen_stages : 1
    norm_eval : True
    init_cfg : 
      type : 'Pretrained' 
      checkpoint : 'torchvision://resnet50'
neck : 
    type : 'FPN'
    in_channels : [256, 512, 1024, 2048]
    out_channels : 128
    num_outs : 4
neck_2d : 
bbox_head_2d : 
backbone_stereo : 
depth_head : 
backbone_3d : 
# neck_3d :
#   type : 'OutdoorImVoxelNeck'
#   in_channels : 64
#   out_channels : 256

valid_sample : True
temporal_aggregate : 'concat'
voxel_size : &voxel_size [0.25, 0.25, 0.25]  # n_voxels : [240, 300, 12]
anchor_generator : 
    type : 'AlignedAnchor3DRangeGenerator'
    ranges : &range [[-10.0, -10.0, 0, 10.0, 10.0, 3]]
    rotations : [.0]

neck_3d : 
    type : 'DfMNeckConv'
    in_channels : 128
    out_channels : 128
    num_frames : 1  # num_frames = num_ref_frames+1


bbox_head_3d :
    type: CenterHead
    in_channels: 128
    train_cfg:
      point_cloud_range: &point_cloud_range [-10, -10, 0, 10, 10, 3]
      grid_size: [80, 80, 1]
      voxel_size: *voxel_size
      out_size_factor: &out_size_factor 1
      dense_reg: 1
      gaussian_overlap: 0.1
      max_objs: 500
      min_radius: 2
      code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
    test_cfg:
      post_center_limit_range: *point_cloud_range
      max_per_img: 500
      max_pool_nms: false
      min_radius: [0.175]
      score_threshold: 0.3
      out_size_factor: *out_size_factor
      voxel_size: *voxel_size
      nms_type: rotate
      pre_max_size: 1000
      post_max_size: 83
      nms_thr: 0.02
    tasks:
      - ["pedestrian"]
    common_heads:
      reg: [2, 2]
      height: [1, 2]
      dim: [3, 2]
      rot: [2, 2]

    share_conv_channel: 64
    bbox_coder:
      type: CenterPointBBoxCoder
      pc_range : *point_cloud_range 
      post_center_range: *point_cloud_range
      max_num: 500
      score_threshold: 0.1
      out_size_factor: *out_size_factor
      voxel_size: *voxel_size
      code_size: 7
    separate_head:
      type: SeparateHead
      init_bias: -2.19
      final_kernel: 3
    loss_cls:
      type: GaussianFocalLoss
      reduction: mean
    loss_bbox:
      type: L1Loss
      reduction: mean
      loss_weight: 0.5
    norm_bbox: true