type : 'MultiViewLSSFisheye'
vehicle : 'Hycan'
num_views : 4
backbone : 
    type : 'EfficientNet'
    C : &C 64
    downsample : 4
grid_conf :
    xbound : [-10, 10, 0.25]
    ybound : [-10, 10, 0.25]
    zbound : [0, 3, 3]
    dbound : [0.25, 15, 0.25]
final_dim : [368, 640] # the image shape after preprocess
normalizer_clamp_value : 10
use_quickcumsum : False
outC : &outC 256
bbox_head_3d : 
    type : 'Anchor3DHead'
    num_classes : 1
    in_channels : *outC
    feat_channels : *outC
    use_direction_classifier : True
    anchor_generator : 
        type : 'AlignedAnchor3DRangeGenerator'
        ranges : [[-10.0, -10.0, 0, 10.0, 10.0, 3]]
        sizes : [
            [0.5, 0.5, 1.74],  # pedestrian
        ]
        rotations : [0, 1.57]
        reshape_out : False
    diff_rad_by_sin : True
    dir_offset : -0.7854  # -pi / 4
    bbox_coder : 
      type : 'DeltaXYZWLHRBBoxCoder'
    loss_cls : 
        type : 'FocalLoss'
        use_sigmoid : True
        gamma : 2.0
        alpha : 0.25
        loss_weight : 0.02
    loss_bbox : 
      type : 'SmoothL1Loss' 
      beta : 0.1111111111111111
      loss_weight : 2.0
    loss_dir : 
        type : 'CrossEntropyLoss' 
        use_sigmoid : False 
        loss_weight : 1.0
train_cfg : 
    assigner : 
      -
        # for Pedestrian
            type : 'MaxIoUAssigner'
            iou_calculator : 
              type : 'BboxOverlapsNearest3D'
            pos_iou_thr : 0.5
            neg_iou_thr : 0.35
            min_pos_iou : 0.35
            ignore_iof_thr : -1
      # -
      #   # for Cyclist
      #       type : 'MaxIoUAssigner'
      #       iou_calculator : 
      #         type : 'BboxOverlapsNearest3D'
      #       pos_iou_thr : 0.5
      #       neg_iou_thr : 0.35
      #       min_pos_iou : 0.35
      #       ignore_iof_thr : -1
      # -
      #   # for Car
      #       type : 'MaxIoUAssigner'
      #       iou_calculator : 
      #         type : 'BboxOverlapsNearest3D'
      #       pos_iou_thr : 0.6
      #       neg_iou_thr : 0.45
      #       min_pos_iou : 0.45
      #       ignore_iof_thr : -1
    allowed_border : 0
    pos_weight : -1
    debug : False
test_cfg : 
    use_rotate_nms : True
    nms_across_levels : False
    nms_thr : 0.01
    score_thr : 0.1
    min_bbox_size : 0
    nms_pre : 500
    max_num : 100