type : 'FCOSMono3D'
backbone : 
    type : 'ResNet'
    depth : 101
    num_stages : 4
    out_indices : [0, 1, 2, 3]
    frozen_stages : 1
    norm_cfg : 
      type : 'BN'
      requires_grad : True
    norm_eval : True
    style : 'pytorch'
    init_cfg :  
      type : 'Pretrained'
      checkpoint : 'torchvision://resnet101'
    dcn : 
      type : 'DCNv2'
      deform_groups : 1 
      fallback_on_stride : False
    stage_with_dcn : [False, False, True, True]
neck : 
    type : 'FPN'
    in_channels : [256, 512, 1024, 2048]
    out_channels : 256
    start_level : 1
    add_extra_convs : 'on_output'
    num_outs : 3
    relu_before_extra_convs : True
bbox_head : 
    type : 'PGDHead'
    num_classes : 1
    in_channels : 256
    stacked_convs : 2
    feat_channels : 256
    bbox_code_size : 7
    use_direction_classifier : True
    diff_rad_by_sin : True
    pred_attrs : False
    pred_velo : False
    pred_bbox2d : True
    use_onlyreg_proj : True
    pred_keypoints : True
    dir_offset : 0.7854  # pi/4
    strides : [8, 16, 32]
    regress_ranges : [[-1, 128], [128, 256], [256, 100000000]]
    group_reg_dims : [2, 1, 3, 1, 16, 4]  # offset, depth, size, rot, kpts, bbox2d
    cls_branch : [256, ]
    reg_branch : [[256,], [256,], [256,], [256,], [256,], [256,]]
    dir_branch : [256, ]
    attr_branch : [256, ]
    centerness_branch : [256, ]
    loss_cls : 
        type : 'FocalLoss'
        use_sigmoid : True
        gamma : 2.0
        alpha : 0.25
        loss_weight : 1.0
    loss_bbox : 
      type : 'SmoothL1Loss'
      beta : 0.1111111111111111
      loss_weight : 1.0
    loss_dir : 
        type : 'CrossEntropyLoss'
        use_sigmoid : False
        loss_weight : 1.0
    loss_attr : 
        type : 'CrossEntropyLoss' 
        use_sigmoid : False
        loss_weight : 1.0
    loss_centerness : 
        type : 'CrossEntropyLoss' 
        use_sigmoid : True
        loss_weight : 1.0
    norm_on_bbox : True
    centerness_on_reg : True
    center_sampling : True
    conv_bias : True
    dcn_on_last_conv : True
    use_depth_classifier : True
    depth_branch : [256, ]
    depth_range : [0, 10]
    depth_unit : 1
    division : 'uniform'
    depth_bins : 11
    bbox_coder : 
      type : 'PGDBBoxCoder'
      code_size : 7
    pred_keypoints : True
    weight_dim : -1
    loss_depth : 
        type : 'SmoothL1Loss'
        beta : 3.0
        loss_weight : 1.0
    loss_bbox2d : 
      type : 'SmoothL1Loss'
      beta : 0.1111111111111111
      loss_weight : 0.0
    loss_consistency : 
      type : 'GIoULoss'
      loss_weight : 0.0
    bbox_coder :
        type : 'PGDBBoxCoder'
        base_depths :  # front object position and back object position
        base_dims : [[0.91, 1.74, 0.84]]
        code_size : 7
train_cfg : 
    allowed_border : 0
    code_weight : [1.0, 1.0, 0.2, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0 ]
    pos_weight : -1
    debug : False
test_cfg : 
    use_rotate_nms : True
    nms_across_levels : False
    nms_pre : 100
    nms_thr : 0.1
    score_thr : 0.01
    min_bbox_size : 0
    max_per_img : 20
