dataset_type : CustomMonoDataset
class_names : &class_names 
    ['car', 'truck', 'trailer', 'bus', 'construction_vehicle', 'bicycle', 'motorcycle', 'pedestrian', 'traffic_cone', 'barrier']

img_norm_cfg : &img_norm_cfg
    mean : [103.530, 116.280, 123.675]
    std : [1.0, 1.0, 1.0]
    to_rgb : false

train_pipeline :
    -
        type : LoadImageFromFileMono3D
    -
        type : LoadAnnotations3D 
        with_bbox : false
        with_label : false
        with_attr_label : false
        with_bbox_3d : True
        with_label_3d : True
        with_bbox_depth : True
    -
        type :  Resize 
        img_scale : [960, 1280]
        keep_ratio : True
        multiscale_mode : value

    # RandomFlip3D :
    #     flip_ratio_bev_horizontal : 0.5
    - 
        type : Normalize
        << : *img_norm_cfg
    -
        type : Pad 
        size_divisor : 32

test_pipeline :
    -   
        LoadImageFromFileMono3D : True
    - 
        MultiScaleFlipAug :
            scale_factor : 1.0
            flip : False
            transforms :
                RandomFlip3D : True
                Normalize : *img_norm_cfg
                Pad :
                    size_divisor : 32
                DefaultFormatBundle3D :
                    class_names : *class_names
                    with_label : False
                Collect3D :
                    keys : ['img']
