model_config : /mnt/pool/cxy/mono3d/configs/models/fcos3d_custom.yaml
dataset_config : /mnt/pool/cxy/mono3d/configs/datasets/custom-mono3d.yaml
data_root : /mnt/pool/cxy/mono3d/data/2024-04-20-15-29-03
save_path : ../ckpt/
annotation_prefix : annotations
image_prefix : images
gpu_id : 0
seed : 2025

optimizer : 
    lr : 0.002
    paramwise_cfg : 
        bias_lr_mult : 2.0
        bias_decay_mult : 0.0
    grad_clip : 
        max_norm : 35.0
        norm_type : 2

epoches : 12

batch_size : 2

eval_interval : 2

lr_config : 
    policy : step
    warmup : linear
    warmup_iters : 500
    warmup_ratio : 1/3
    step : [8, 11]

